### ISSUE TITLE
Diversity curve generator only uses the collections in the map view to plot diversity. This is NOT obvious nor apparent.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#101]

**Comment by markuhen** [comment]
I think we need to change the entire Navigator system to plot everything all the time. We should NOT change the scope of the collections as you zoom in the map. This is proving to be VERY confusing to end users. This should simplify the code behind Navigator, which is malfunctioning anyway, see #98.

**Comment by vjpsyverson** [comment]
I think the best solution to this overall would be to stop filtering by screen extent and add a feature that allows the user to draw a bounding box manually. I'm picturing it as a tool that you would select from the bar, drag over the desired region to highlight it (i.e. gray out the rest of the map), and then you could zoom independent of the bounding box. It could then be given as a filter option in the filter box in the lower left corner as "(0.00 N, 0.00 E) x (1.00 N, 1.00 E)" and deleted the same way the other filters are. 

Until that's implemented, though, we don't have any way to geographically restrict other than by screen extent. Would it be better not to do it at all than to do it the way we currently do, @markuhen?

**Comment by mmcclenn** [comment]
Unfortunately, this change has still not been made. I have been focusing on data entry, and haven't had time to delve into the Navigator code. I didn't write that code, and would have to take some time to figure it out before I can make any substantive changes to it. I would love to do a thorough overhaul of Navigator, if we can find some funding somewhere to do that.

**Comment by markuhen** [comment]
I think for now we just need to make it super clear on the diversity curve screen that it is plotting what was on the Navigator screen. That should suffice for now.

**Comment by vjpsyverson** [comment]
I've added a simple fix for this: it now just displays the lat/long values it's sending to quickdiv at the top right of the diversity modal. The awesome potential improvement discussed above has been moved to #112.
