### ISSUE TITLE
Display the Resources tab on the menu bar in Navigator.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#103]

**Comment by vjpsyverson** [comment]
I'm not convinced this is a good idea. Currently the nav bar in Navigator contains only things relevant to Navigator, plus a link back to the front page. (In fact, it's got an "About" that is entirely distinct from the "About" on the splash page!) If we're going to start cross-pollinating, I think we ought to consider a total redesign of the Navigator bar.

@markuhen, change my mind: do you have some specific reason why you think it's important to get from Navigator to the Resources page in one step?

**Comment by markuhen** [comment]
This one was a request from someone else. I agree it seems inconsistent, and just as a personal guide I think we should maximize consistency of the menu bars we display to minimize barriers to use. If it is not practical here, then so be it!

**Comment by vjpsyverson** [comment]
You got it!
