### ISSUE TITLE
Problem with taxon tree lookup in Occurrences tab?

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#118]
The taxon page clearly shows this as belonging to Cetacea...
![Screenshot 2020-02-08 at 12 14 06 PM](https://user-images.githubusercontent.com/16811399/74091464-bd3c7200-4a6c-11ea-87b0-311a66473b24.png)
...but on Navigator it shows up as NO_FAMILY_SPECIFIED.
![Screenshot 2020-02-08 at 12 13 47 PM](https://user-images.githubusercontent.com/16811399/74091468-c9c0ca80-4a6c-11ea-8d80-6e711b771799.png)
Anyone have any idea what's up with this?

**Comment by markuhen** [comment]
Valerie,

Yes. Because this:

'Parietobalaena belongs to Cetotherioidea' according to P. Gol'din and 
M. E. Steeman 2015

Is the opinion in effect. It is in a superfamily, but not in a family. 
It is working as designed and not a bug.

Thanks,

Mark

On 2/8/20 3:16 PM, V. J. P. Syverson wrote:
> The taxon page clearly shows this as belonging to Cetacea...
> Screenshot 2020-02-08 at 12 14 06 PM 
> <https://secure-web.cisco.com/1qZREyKacaMIgAjEaq2XNr2g2_TdIqa4qkKzKFHSEdz16Y-ZZfl8qr73rZHc4HJxblytVb67ygr8HQPwrePBYraAP5BJR2k5SyCYQctSvayQ3BYDknAzJTf6IlKzBNMxn8VAflHlMVi_Bao5Lcx3cK81Zak01EoCEnjBdxOv8zIzXi49lDA9hObwfo_qx8bxrb7bahBN1SHMBWwH9IUaIhFXQU3Nn5reMrV5q1xryDivn-rXAch3_r9GGNPZon2NtRIOv_sRP-qg80DAqMUk_cmNp89cL8dVEXyd2Q4eqICh2_GX7NElaWKyC0R5_j-kTl5T2fdfUN87jh4-GDqGtF1UUTXvh76jSg6vTnX9wzGAzSJPnEdBQ-WcPh4xoNq_W3XXIv238LzDRgX20fklVV0obDbSlda6TgDVcHBOSbkOtYeS4OjAfR8-seDSJnA9pBjVw-38Lpa3Ld9TfXDjVbg/https%3A%2F%2Fuser-images.githubusercontent.com%2F16811399%2F74091464-bd3c7200-4a6c-11ea-87b0-311a66473b24.png>
> ...but on Navigator it shows up as NO_FAMILY_SPECIFIED.
> Screenshot 2020-02-08 at 12 13 47 PM 
> <https://secure-web.cisco.com/1ysuP_prf_uQQWujcXnOMsSMY0cA_KnWxM7N_SSnkc7PqkUnBr0buLIFlOMSxyxNYin3BjZbBqcvS7820ObgDWlE7KMeEWfjpGz57qvw4i5lyMNWUfxzvwo6UV1YUX2JxKpQYI3miC1Qh45FOjI9WhwOc2PVruaARDFhPR4IrUUvWxc_IYT3HaLml82V0i7pY7nOOInnCyppNWeMYTDfV_bNfI03oWiXHbm3zOPMbH1mgGk13BBf4xCkMAYFEdNLW2iEWJuIibPrSxO8iKlIUwkr6NN2DTWYgLx6KOyW2_ATXGbnL4-bBrShNJtEnULcwhYq-fQWqW8_4_F2W808cXfk8CrNHN5SgFAVkTpW2-a5XFs2Me6CbbSST0qBDRzdtKutj7aU9mVqKuFkQ1JDVHmT2XfXLrUPebdVsF-sbwZKRcUxUrp-TwOKm5FbLFy14yudfok3941rBL-9gHF_7_g/https%3A%2F%2Fuser-images.githubusercontent.com%2F16811399%2F74091468-c9c0ca80-4a6c-11ea-8d80-6e711b771799.png>
> Anyone have any idea what's up with this?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/1sjc1xoCOs7kVY5s4sRqDeWU-w27tribVJEgFy2kcVD7eh2VKbjnLby8tO8Oh3HsPInbuf05nmIU667Ipc8yg4rdrmhP0f1zmx_6dHOfmIXxHudd3WWEduobsTGMF20p-Wp1YX8_Ob1yiVZ5N1uVR1un-mwIp8Ww4PrsXBViS6Rp8Yf_uuUMgVnug28mhpyqZVHCJPcbtRD3V6lj5OlgYmzY9xFNOIBV7KcZ6ijEKOEm57DEJIs16Qo0Kmwam0yw-I9b9lHil-RCa1J-4UU2BN8Jwo4Mb9hheFLY0zRmc-e2ZNfKAKN6iMwwK-G82j_lYilsAyOEFqMsYky8e5PiRp7XmHx8SSaVfa237LXHFJdeaj5UlVhaMdEBvWgMj-fPG9yHJ-XdrskbPGZau2vz4Njxi08KaJXy1kHNGKq9VazzQa1HJ2U-iqKDsZdOiNkuT/https%3A%2F%2Fgithub.com%2Fpaleobiodb%2Fnavigator%2Fissues%2F118%3Femail_source%3Dnotifications%26email_token%3DAEVGYTASUY35YEUBGKP25LLRB4HJJA5CNFSM4KR4XEX2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IMARGYA>, 
> or unsubscribe 
> <https://secure-web.cisco.com/1PPZvVEN23ax5PN6MNY5gRV6hgiXhf4aRwOar3Sa! 
> w1UEtE3xBp3yfWldiI5LqiQcwdu7KkNRDTJHVnBD2yTQe4U4kcbNSlN1wj0HmFn7PFFgXv5o3KhzUYrAidgKUBKv6DM_iwTn4kwGYoFRL_r70snPxm6NECQKoAxZ_cZmrGxqo_zCHEm2-ddCiwn4yf2CsER_kQlPsq90tZQ7f9ofnII3BdTcK6ikfsuvLOTq12NZC8hSAFbCPX0JrxR3L_v2FtR4qBViNaNPD06tWu_ZPG9HhdUXbp4RsiE7c_mq7Na8ePI0SsnZG2Kk2EeG1vEwkngj_pi-RsWf6na2_RJlHY_Kx4U6kh2KKFGi4EchM6OzJcPTDuHBCe37WKmpRygC0A1QCiERznOz4IsFoCwXLlFqvSo-jHWj64J9Wgnz2ky3rZ3nqYvkhC5koPWC71_kg/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEVGYTE2HK4IFGKNVUKXWTLRB4HJJANCNFSM4KR4XEXQ>.
> 

-- 
Mark D. Uhen
Associate Professor & Associate Chair
George Mason University
AOES Geology
MSN 6E2
Fairfax, VA 22030
Phone: 703-993-5264
Fax: 703-993-3535
