### ISSUE TITLE
Application State URL generator does not appear to be working

### ISSUE THREAD

**Issue by stemcelltulsa** [paleobiodb/navigator#120]
Trying to share a search/view somehow if possible, but the url box remains empty. An embed feature would be nice but I'd be okay with a link generator.

**Comment by cambro** [comment]
The state URL does indeed seem to be broken. This is introduced behavior at some point recently so we will attempt to track it down. Thanks for pointing it out.

**Comment by cambro** [comment]
@mmcclenn would be good to push this up on the to-do list at some point.

**Comment by mmcclenn** [comment]
Fixed. There was a missing column in the navigator_states table.
