### ISSUE TITLE
Unable to launch application

### ISSUE THREAD

**Issue by kairogers1** [paleobiodb/navigator#126]
I am unable to view the PBDB Navigator, the screen just reads, "Initializing Application, please be patient, It may take a moment." Are there any troubleshooting tips for this?

**Comment by davenquinn** [comment]
Just tested in Firefox and Safari, and https://paleobiodb.org/navigator/ appears to boot as normal for me. Perhaps you can refresh the page to clear the cache?

**Comment by pnovack-gottshall** [comment]
The global restart was just done, which seems to have fixed things. Please re-open if returns.

**Comment by cambro** [comment]
Fixed with pbdb restart; as yet unsure of cause of outage.
