### ISSUE TITLE
Frame Overlap Issues in Navigator 1.0 with Firefox

### ISSUE THREAD

**Issue by dwbapst** [paleobiodb/navigator#13]
I seem to have found a graphics issue on a Windows 7 machine with Firefox 38.0.5, where frames overlap in ways that obscure or make it difficult to navigate options. I'm unclear if these are 'as intended' and thus my issue is really a feature request, but it doesn't seem like optimal graphics implementation.

First, the right-side prevalent taxon list is obscured by a blank box that seems to exist for the 'hover text' you get when you place your cursor over a collection, and can even continue past this box to sit partly behind the time-scale at the bottom. Although you can partly see the obscured prevalent taxa in this lower portion of the prevalent taxa menu, you can't access them, or scroll down the prevalent taxon menu. Here's an example, where you can see the '%' of a prevalent taxon peaking out behind the black bar of 'geologic time':

![navigator_screenshot_06-25-15crop](https://cloud.githubusercontent.com/assets/1561903/8358168/1bb05796-1b1c-11e5-9a00-8939132e1c83.jpg)

I imagine the lower bound for the prevalent taxon list needs to be cut higher? I'm not certain why the blank hovertext box has to exist if no hovertext for a collection is being called, so if it was removed, there'd be more room for accessing the prevalent taxa. 

Also, and I realize this gets into feature request territory, but it would be nice to navigate downwards through the prevalent taxa past the first few most prevalent taxa.

This is probably an old issue, but a similar frame overlap occurs on the right-side of the main Navigator menu if you select too many filters, making it difficult to remove filters at the top of the filter bar.

![navigator_screenshot_06-25-15](https://cloud.githubusercontent.com/assets/1561903/8358037/4c10d9f2-1b1b-11e5-9cf9-7a069df9d935.png)

Perhaps shift the filters slightly rightwards if enough filters are added that the filter menu reaches the bottom of the main menu?

**Comment by cambro** [comment]
Agreed that point 3(?)/last one that this is not elegant, but we do not intend to account for all user decisions (like the example shown, which does not actually filter anything below "Plantae"). 

Note that the number of filters that "fit" is a function of screen size, which varies wildly. It is not worth adding complexity to the code that will capture only a very few situations. And then....Is it better to arbitrary restrict filter number, or allow for multiple filters, inelegantly displayed?

**Comment by dwbapst** [comment]
That's fair. All of the above issues I raise are ultimately about aesthetics, except maybe for the practical inability to access/view beyond the first five prevalent taxa on the right-hand menu.

After all, I am documenting these issues without knowing the context of whether they were intentional design decisions or not. That's a typical QA scenario. If these aesthetic issues are working 'as intended', then okay.

**Comment by cambro** [comment]
I think it's a mix of intentional and bugs. There are definitely differences in rendering behaviors of browser brands and OS implementations. Sometimes code tweaks can fix them, sometimes they can't.

It would be great if you forked Navigator and identified these fixes and submitted pull requests! ;)
