### ISSUE TITLE
Missing time scale numbers at the bottom of the screen

### ISSUE THREAD

**Issue by AnnaCordes** [paleobiodb/navigator#132]
Hi, we are using this website at our school, and we used to be able to see the timeline at the bottom of the page to see how long ago these fossilized animals lived, but it's not there anymore.  Did I click something to make it go away?  Or has the site changed?

Thanks!
Anna

**Comment by mmcclenn** [comment]
You are right, the time scale numbers have disappeared. For some reason, I hadn't noticed that. I will see if I can figure out what went wrong, and get them displaying again. Thanks for letting us know!

**Comment by AnnaCordes** [comment]
Yay!  Glad I emailed you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmcclenn** [comment]
The timescale ticks and year numbers are back. You will have to do a full reload on the page (or clear your browser cache) to see them, because you need to force your browser to reload the Javascript file that runs the map/timescale display.
