### ISSUE TITLE
Diversity Curve under Stats shows Two Overlapping Period Labels

### ISSUE THREAD

**Issue by dwbapst** [paleobiodb/navigator#14]
If you go to Stats, the labels for periods on the provided diversity curve shows both the full name of periods and the abbreviated letterlabels for the names of (some of) the periods, overlapping each other rather uncomfortably.

Here's an example, for the best class in the Metazoa:

![navigator_divcurve_screenshot_06-25-15](https://cloud.githubusercontent.com/assets/1561903/8358361/fdb59930-1b1c-11e5-9adf-e14d146c54e2.jpg)

My guess is that there's some rule that says that if there's enough room to print the full name of the period, but that rule isn't communicating to not print the abbreviated name in addition.

**Comment by cambro** [comment]
Please post your OS and browser when reporting rendering bugs. This works fine on most browsers we have tested:

![grap](https://cloud.githubusercontent.com/assets/6107153/8359737/d1b87f3a-1b2d-11e5-9813-831f9f06ba0b.png)

**Comment by dwbapst** [comment]
Apologies; Windows 7 machine with Firefox 38.0.5.
