### ISSUE TITLE
Add () to subgenus name in autocomplete menu

### ISSUE THREAD

**Issue by cambro** [paleobiodb/navigator#17]
This displays properly once selected, but is confusing when showing as a subgenus with no ()

**Comment by vjpsyverson** [comment]
Can you give me an example?

**Comment by vjpsyverson** [comment]
This will be part of the bundle of autocomplete changes that @mmcclenn is working on. The goal is for the autocomplete to have its own API call, I think, and once that's exposed Navigator will be updated to use it.

**Comment by vjpsyverson** [comment]
This is working now.
