### ISSUE TITLE
Improve download button and options

### ISSUE THREAD

**Issue by aazaff** [paleobiodb/navigator#21]
- [x] Change download button icon.
- [x] Add link to advanced download form
- [x] Add link to Phoebe Cohen Navigator walkthrough to page - (next to help button)

**Comment by vjpsyverson** [comment]
Icon is changed in "edu" branch which is presently running on teststrata -- go have a look.

Links to advanced download form and walkthrough will be added in branch data2.

**Comment by vjpsyverson** [comment]
@aazaff, do you like the new buttons in the version on training?

**Comment by vjpsyverson** [comment]
I am filing # 3 as a separate issue, because I'd like to discuss it further.
