### ISSUE TITLE
Undefined Application state URL

### ISSUE THREAD

**Issue by jmarcot** [paleobiodb/navigator#28]
I made a figure (screenshot) of a Navigator map for a course I am teaching, and I am attempting to generate a URL to send to my class, so students can start with the map and data in that image, then explore it themselves. If I understand it correctly, this is what the Application State URL is intended to do, but when I click the "Get URL" button, I get the following URL:

https://paleobiodb.org/navigator/#/undefined

**Comment by jczaplew** [comment]
Fixed.

**Comment by cambro** [comment]
@jmarcot thanks for posting this issue, and sorry for the delay getting it buttoned up.
