### ISSUE TITLE
Add signup instructions to Contact page

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#34]
per @markuhen:

Can you update the Contact Us page (https://paleobiodb.org/#/contact)
to include instructions as to how to request an account?

I think all we need to do is add a link to the login page for them to sign up for a guest account (https://paleobiodb.org/login). The instructions are there, but for some reason, no link.

**Comment by jczaplew** [comment]
I think this issue is intended to be on the `pbdb-main` repo?

**Comment by vjpsyverson** [comment]
yep
