### ISSUE TITLE
Navigator total of collections/occurrences does not update when changing to a time period with zero collections

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#36]

**Comment by vjpsyverson** [comment]
This is the same as issue #18 and will be resolved in the same branch that updates to data1.2.

**Comment by markuhen** [comment]
There is still something wrong with this. See the images below. In Zoom 1, there are 3 collections displayed with a total of 5 occurrences. In Zoom 2, the same 3 collections with 5 occurrences are displayed, but the number of collections reads 0. This is impossible!

![eocene cetacea zoom 1](https://cloud.githubusercontent.com/assets/19557452/25238283/ff0aac26-25ba-11e7-8385-994aaa8a482f.jpeg)
![eocene cetacea zoom 2](https://cloud.githubusercontent.com/assets/19557452/25238287/02464148-25bb-11e7-90b9-66ecff353d5d.jpeg)

**Comment by vjpsyverson** [comment]
This is a different problem -- it's not a "does not update" problem as stated in the title (and in #18) but rather an issue in reporting the number of collections. I will move it to a new issue and mention it in the beta testing repo.

**Comment by markuhen** [comment]
Please keep it off of the Beta testing until we get a potential solution. Thanks!
