### ISSUE TITLE
Navigator should only use accepted names of taxa. It appears to be plotting anything in a taxonomic list without resolving the name, but I'm not sure.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#37]

**Comment by vjpsyverson** [comment]
Can you give me an example of how to replicate this bug?

**Comment by markuhen** [comment]
Let's plan to look at these when I am in Madison tomorrow. Just let me know when and where to meet you!

**Comment by markuhen** [comment]
If you search for the Taxon Pinnipedia on Navigator, and then click on Eocene, a single dot appears in northern Europe. Click on it and look at the taxon list. It lists Praephoca bendullensis n. gen. n. sp. The opinion in force identifies this taxon as a nomen dubium in Phocidae, so I would think it should show Phocidae indet. there or at least indicate it is a nomen dubium. I think we just need to show a different name field here, as we have lots of them, but let's check with Michael to see A) what it is displaying now, and B) what it should perhaps display instead.

**Comment by jczaplew** [comment]
This is the data service call made for the case mentioned above:

https://paleobiodb.org/data1.1/occs/list.json?coll_id=121968&show=phylo,ident&interval_id=37&base_id=53270

**Comment by markuhen** [comment]
Also check the taxon Mesocetus. The one showing up in Egypt is NOT correct. It is a homynm of the real Mesocetus which shows up across Europe and North America. Interestingly, there is yet another Mesocetus which is a synonym of Diaphorocetus in South America which does NOT show up on the map.

**Comment by markuhen** [comment]
When we change Navigator to 1.2, change the displayed taxon names to accepted name vs. whatever it shows now.

**Comment by vjpsyverson** [comment]
I don't think this problem with _Mesocetus_ is in Navigator. The database has the accepted_name('tna') as _Mesocetus schweinfurthi_ for that occurrence.

https://paleobiodb.org/classic/basicCollectionSearch?collection_no=45626
https://paleobiodb.org/data1.2/occs/list.json?coll_id=45626&show=phylo,ident&base_id=36762

**Comment by markuhen** [comment]
There is definitely something wrong with PBDB re: Mesocetus. We are tracking it down. But, we need to make sure that Navigator is always using the accepted name. Can we confirm that? The Pinnipedia example seems to be working correctly.

**Comment by mmcclenn** [comment]
I'm updating the auto-completion code now, so that it will (1) always use accepted names and (2) include homonyms where appropriate.
