### ISSUE TITLE
Problems with /#/ in the PBDB splash page

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/navigator#40]
Resources external to the PBDB web application (ie. assets managed in pbdb-main) insert a # before most page links such as #/resources.

This functions as both a jump-to anchor in the resulting page but also triggers the appropriate JavaScript code to generate the page in the first place thus it can not be omitted.

Online forms which allow the attachment of URLs to show examples of work have been found to reject the URL because of this symbol. In particular, NSF does not allow it!

Request the # symbol as the root of the JS code be changed to something else.

**Comment by jczaplew** [comment]
Moved to https://github.com/paleobiodb/pbdb-main/issues/41
