### ISSUE TITLE
When you ask Navigator to display a taxon that is an unresolved homonym, it displays one of them taxa, but needs to ask which one you want to display.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#47]
For example, I asked Navigator to display Probscidea. I got a very strange distribution, and realized it was displaying an insect group called Proboscidea, not the mammalian order Proboscidea.

I think in cases like this Navigator needs to ask which group you want displayed like Classic does, displayed below.

![probscidea](https://cloud.githubusercontent.com/assets/19557452/24910597/3e95d504-1e96-11e7-8823-f88615927f55.jpeg)

**Comment by mmcclenn** [comment]
I will update the autocomplete operation to provide additional information; the autocomplete code needs to be updated to display it.

**Comment by markuhen** [comment]
I have reactivated this bug and moved it to the highest level of alert. Indeed, we have an autocomplete function that APPEARS to let you select only the mammals, but it is still mixing up the the insects with the mammals when you map Proboscidea.

**Comment by markuhen** [comment]
Here is more data on the current problem from the person who reported it to me. We need to fix and thoroughly test this ASAP.

I had seen that option myself [the current autofil option to slect Proboscidea Mammalia], but when I select it it only shows the insects regardless (while the search bars recognize there is a mammalian proboscidea, it fails to actually recognize that when trying to map taxa; if moving upward (say, from elephantoidea or elephantiformes to proboscidea, it also automatically changes over to the insect group).

This is most obvious on the maps too because it shows lots of stuff predating the cenozoic, whereas probosidean mammals (elephants and such) only show up starting around 60 mya. The workaround I've found is just to target all of the subtaxa contained with proboscidea, but it's a suboptimal solution.

**Comment by jpjenk** [comment]
Issue has been fixed, pending merge into master branch and pull to production.
