### ISSUE TITLE
When Navigator is using data 1.2, dots disappear from paleomaps

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#55]
Dots look great in the Recent map and disappear when you plot them on paleomaps.

![eocene cetacea](https://cloud.githubusercontent.com/assets/19557452/25185753/31090792-24ec-11e7-8c88-8ba2f274ed0b.jpeg)

**Comment by mmcclenn** [comment]
Is this still happening after my fix for #56?

**Comment by markuhen** [comment]
Yes. I just cleared my cache, reloaded, and reproduced the exact error pictured above on the training site.

**Comment by mmcclenn** [comment]
Valerie is investigating to see whether this is a navigator issue or a data service issue.

**Comment by jczaplew** [comment]
The dots come from cached files, which haven't been updated in 3 years.

The cached collections can be found here -  https://github.com/paleobiodb/navigator/tree/master/build/js/rotatedIntervals

The script to update them can be found here - https://github.com/paleobiodb/navigator/blob/master/assets/js/utilities/build_rotation_cache.js

**Comment by vjpsyverson** [comment]
Fixed in edu, please test on training @markuhen

**Comment by markuhen** [comment]
This appears to be working well on Training. I tested Eocene Cetacea, Jurassic Dinosauria, and Miocene Gastropoda.
