### ISSUE TITLE
Number of collections is reported inaccurately

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#57]
from @markuhen:
There is still something wrong with this. See the images below. In Zoom 1, there are 3 collections displayed with a total of 5 occurrences. In Zoom 2, the same 3 collections with 5 occurrences are displayed, but the number of collections reads 0. This is impossible!

![eocene cetacea zoom 1](https://cloud.githubusercontent.com/assets/19557452/25238283/ff0aac26-25ba-11e7-8385-994aaa8a482f.jpeg)
![eocene cetacea zoom 2](https://cloud.githubusercontent.com/assets/19557452/25238287/02464148-25bb-11e7-90b9-66ecff353d5d.jpeg)

**Comment by markuhen** [comment]
This appears to be fixed.
