### ISSUE TITLE
Authorizer filter does not filter displayed data

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#62]
"You can search for data by authorizer, including me (yeah!), but selecting an authorizer has no effect on the data plotted on the map. It remains whatever you had before selecting an authorizer. Taxa, time, and stratigraphy seem to work fine." - @markuhen

**Comment by vjpsyverson** [comment]
I think this is happening in the data service.

**Comment by vjpsyverson** [comment]
To be more specific: 
- in occs/prevalence, I don't think the "occs_touched_by" parameter is working
- in colls/summary, similarly, I think "colls_touched_by" is not working
...because they both return the same number of records regardless of the value of the parameter passed. (i.e. I'm pretty sure I, prs:710, and Mark, prs:180, have not both touched 3590 collection records!)

These are the two calls made by the person filter routine.

**Comment by vjpsyverson** [comment]
@markuhen , do we want the person filter to show all the records touched by a person, or just those for which they're the authorizer or enterer?

**Comment by markuhen** [comment]
Authorizer or enterer.
