### ISSUE TITLE
Download modal passes bad parameter 'showsource'

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#63]
"I just had a global map of Cetacea. I went to download, chose CSV and occurrences and got this response:

400 Bad Request
unknown parameter 'showsource'

The same response is shown for any other data format as well. Occurrences and References fail in the same way for all data formats. Diversity Summary and Full Diversity Method download fine in any format." - @markuhen

**Comment by mmcclenn** [comment]
should be 'datainfo' instead.

**Comment by vjpsyverson** [comment]
thank you Michael!
