### ISSUE TITLE
Taxon browser is not handling data correctly

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#64]
"Something is terribly wrong with the Taxon Browser, but I can't begin to tell you what! See below for Cetacea:
![undefined cetacea](https://cloud.githubusercontent.com/assets/19557452/25352026/9a2f87d6-28f8-11e7-8332-49525df6bb76.jpeg)"

**Comment by vjpsyverson** [comment]
Parameter 'gid' in taxon return is no longer valid, which breaks the taxon browser code. @mmcclenn, what has this been renamed to?

**Comment by mmcclenn** [comment]
That field is now 'oid', which is generically the "object identifier" field. It will contain a value of the form "txn:nnnn" where nnnn is the value that would formerly have been returned by 'gid'.

If the record represents a variant of this taxonomic name other than the currently accepted one, there will also be a 'vid' field which will contain a value of the form "var:nnnn" where nnnn is the key (taxon_no) corresponding to the variant name.

**Comment by mmcclenn** [comment]
I have figured out the main problem indicated for this issue. It's a bug in the data service, which I will work on right now.

**Comment by mmcclenn** [comment]
Data service bug is now fixed on teststrata. You still need to update the code to use 'oid' instead of 'gid', but otherwise it should work okay.

**Comment by vjpsyverson** [comment]
The documentation for taxa/single says it should be returning parameters of
the "**c" subcount group (phc, clc, odc...) but it does not appear to be
doing so. (compare 1.2
<https://training.paleobiodb.org/data1.2/taxa/single.json?id=txn:19346&show=attr,nav,size>
vs 1.1
<https://training.paleobiodb.org/data1.1/taxa/single.json?id=19346&show=attr,nav,size>
for Redlichiida)

**Comment by vjpsyverson** [comment]
To clarify that last comment: I don't NEED it to report the subcounts, I just wanted you to know that it's not doing what the documentation says it's doing. This is ready to test.
