### ISSUE TITLE
Downloader fails when not filtered

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#67]
When you try to download the entire database, it gives a 400 error right now. Adding any filters makes it work normally.

To replicate: load page, hit download all.

Obviously the error is not the desired behavior. How do we want to treat this case, though, @markuhen , @cambro ? @mmcclenn ?

**Comment by markuhen** [comment]
Let's let them download the entire database. I think it should just show a warning if you are trying to download above X records, but I'm not sure what X would be. I would set it at a point where the download would take more than 30-60 seconds to perform. Other thoughts?

**Comment by vjpsyverson** [comment]
I think this is the last 1.2 bug -- at least the last one anyone's told me about. It's an easy fix but I would like @mmcclenn's input also before I go ahead and do it.
