### ISSUE TITLE
Genus navigation filter throws error in ‘Occurrences’ 

### ISSUE THREAD

**Issue by antoniokaplan** [paleobiodb/navigator#82]
In the 'Summary Bin' under the Occurrences tab, there is an error when you click the genus. I will create a pull request to fix this, it looks like a simple change.

![occurrences_error1](https://user-images.githubusercontent.com/759942/26997153-2c179a4c-4d2c-11e7-8451-c7716f312870.png)

**Comment by vjpsyverson** [comment]
I think the problem is in how the genus/species names are assembled by /build/partials/occurrences.html. Working on it right now.
