### ISSUE TITLE
All dots disappear on the first zoom in from the global map.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#84]
This is urgent. Please fix immediately.

I tried two different plots: 1. Chattian, Cetacea; and 2. Late Cretaceous Dinosauria.

This happens on the live site and Training as well.

**Comment by markuhen** [comment]
More info: This appears to be associated with adding the Taxon filter. Plotting just Chattian or just Late Cretaceous shows the dots. Dots reappear on zoom in one more step, and zoom out, but always disappear on the first zoom in from the ovate globe map.

**Comment by mmcclenn** [comment]
Everything appears to be working fine now. This issue can be re-opened if we are ever able to replicate the bug.
