### ISSUE TITLE
smart phone display looks different

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#87]
When you look at Navigator on a smart phone (I think they were all iPhones having this problem) you don't see the toolbar or timescale. Is this by design? If so, is there any way to compensate for their not being there?

**Comment by jczaplew** [comment]
Indeed it is by design. I gave a talk about this at FOSS4G in 2014 - http://www.johnjcz.com/presentations/foss4g2014/

**Comment by markuhen** [comment]
Done!
