### ISSUE TITLE
Chromebook display wrong

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#88]
We had an instance of Navigator being displayed too wide (by like 10%) on a
    Chromebook, obviously running Chrome. So, there was no way to get to
    the rightmost time periods like the Pleistocene because it displayed
    off the screen. On these devices there is apparently no way to
    resize the window.

**Comment by vjpsyverson** [comment]
This is true on my Chromebook too. Looking into it.

**Comment by vjpsyverson** [comment]
@markuhen , is this still happening?

**Comment by markuhen** [comment]
Val,

This was reported to me and I don’t have a chrome book so don’t know.

Sorry,

Mark

Mark D. Uhen

On May 14, 2018, at 7:10 PM, V. J. P. Syverson <notifications@github.com<mailto:notifications@github.com>> wrote:


@markuhen<https://secure-web.cisco.com/1mg_Z6wgfRF_onKluyMXSJnydPLF3usannGwCUvEV0oHB6_sJAXjKLWkS_oFarboSpAOkNnpj5i_-la3dLO-SxNqRqZ8R3yvgNF4YWql1Hp1ITmiPlcI7V8cmBnAbZn_7JoOmrvitHNWpKhfPmKqG_97WqGygkY2K0WZeSGwk_Q6SavJz3QYWFbWzP9QZ89Rgj5PxUq0ONcgVBjVw73u-RsRRN8tf3ByVjXdokgQj_GQFv--LFkis1J_WDOwazfjAFb39UIhQQ0nK0BLKAZGepx7QDOBBhVQbVI1wA0CKp186FAsHf7b11V5N_xAJNyu-sOrpdNPaNlWBKyoAEooNXFHLmbDiPwLfSmvBl5RzFgKFnQJGd049R9L5TUzDp5EmgHdhF-aop4WicrGsjH2l2BALdtfM6EIoJykndJfQa147KnpeNrsV3DGZZ7oAq_l8/https%3A%2F%2Fgithub.com%2Fmarkuhen> , is this still happening?
