### ISSUE TITLE
Species without occurrences listed as having (1) occurrence

### ISSUE THREAD

**Issue by dwbapst** [paleobiodb/navigator#9]
A minor issue I stumbled across. Some taxa in the PBDB have no occurrences listed for them (not sure how that happens), but Navigator mistakingly appears to report these taxa as having '(1)' occurrence.

Here's a reproducible example: Search and filter for genus 'Dicellograptus'. Go to Taxa Browser. Select '4 Species'. Four species are listed, each with a single occurrence. Select and filter on 'Dicellograptus gravis', which is listed as having (1) occurrence, and remove the Dicellograptus filter. Download occurrence data and look at it: no occurrences! Inspection of PBDB Classic and the API confirms no occurrences for Dicellograptus.

![gravis_02-12-15](https://cloud.githubusercontent.com/assets/1561903/6174796/797785ec-b2ae-11e4-907c-7b31f19de7e3.jpg)

**Comment by cambro** [comment]
Ah, thanks for this catch. We will push a fix soon.

**Comment by jczaplew** [comment]
Thanks for the catch!

Here is the URL being used to produce that result:
http://paleobiodb.org/data1.1/taxa/list.json?id=33650&show=size&rel=all_children&rank=3

It seems that the ````(1)```` is coming from the ````siz```` parameter, which the API defines as "The total number of taxa in the database that are contained within this taxon, including itself", which admittedly is not occurrences. 

I think think this is actually more of an interface bug, as we claim that those numbers refer to the number of occurrences in the database, when actually they refer to the number of taxa. I'd like to propose simply changing ````(number of occurrences in the database)```` to ````(number of taxa in the database)````. 

Do you think this would be a sufficient fix?

**Comment by dwbapst** [comment]
Ah, I missed your bottom question until just now. If that question was to me, yes, that sounds like a sufficient fix. However, you might *also* want a notification box to pop up if users filter on a taxon that has no occurrences (actually, that might be useful if a user's search filter produces 0 occurrences regardless of cause... i.e. filtering on Trilobita in the Cenozoic...).

**Comment by jczaplew** [comment]
I'm going to consider this fixed in the version of Navigator that will be released shortly. 

As for filter combinations that produce 0 occurrences, that was discussed in #1. It is not something that will be added soon, but if you'd like to add that feature feel free to submit a pull request!
