### ISSUE TITLE
menu errors for public users

### ISSUE THREAD

**Issue by cambro** [paleobiodb/navigator#90]
From Download Data button on main page -> Action Menu
The following options return errors:

https://paleobiodb.org/classic?a=displayOccurrenceAddEdit
returns "Server Error Please contact the database administrator"

https://paleobiodb.org/classic?a=displayOpinionSearchForm
returns "Can not open template search_taxon_form"

https://paleobiodb.org/classic?a=displayAuthorityTaxonSearchForm
returns "Can not open template search_taxon_form"

**Comment by markuhen** [comment]
I don't see these errors. I am using Chrome. Any more details on browser and such?

**Comment by markuhen** [comment]
When I click on Shanan's URLs above I get these errors, but I'm not sure how these URLs were generated.

**Comment by jczaplew** [comment]
Just to confirm, this is the download form of Navigator and not the primary [download page ](https://paleobiodb.org/classic?a=displayDownloadGenerator)?

**Comment by jpjenk** [comment]
Action menu is now disabled (and hidden) for all non logged-in browsers in addition to logged-in Guest users. Therefore, problematic links described above are no longer accessible.
