### ISSUE TITLE
Navigator number of collections and occurrences appear to be wrong.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#98]
When using the PBDB Explorer and filtering on the Cenomanian stage, the system displays an occurrence count of 144395. When using the diversity end-point, a value of 20216 is returned for number of occurrences.

API Link:
https://paleobiodb.org/data1.2/occs/diversity.json?interval=mesozoic&base_name=life

Screenshots:
![31309274-9dfe55fa-ab51-11e7-90a0-30e17a03ba63](https://user-images.githubusercontent.com/19557452/35246526-0934e982-ff95-11e7-912d-ed1712eccc93.png)
![31309275-a4e9f130-ab51-11e7-93c6-d9a3a041252a](https://user-images.githubusercontent.com/19557452/35246532-0b3933fa-ff95-11e7-9067-7cc88d97b670.png)
![31309279-b774139e-ab51-11e7-8f83-276751097d4b](https://user-images.githubusercontent.com/19557452/35246536-0d440896-ff95-11e7-8015-449f44abe621.png)

**Comment by markuhen** [comment]
Looking at a download of Cenomanian data, it looks like the number the Navigator is reporting as the number of total collections is very close to that which the downloader reports for the number of occurrences. The number of occurrences reported by Navigator seems WAY too high.

**Comment by markuhen** [comment]
This might be a recurrence of #57.

**Comment by jpjenk** [comment]
Investigating a potential error in computing the summary statistics in the data service. Navigator also appears to be making two identical calls to data1.2/colls

**Comment by vjpsyverson** [comment]
So is this a Navigator issue, or is the API returning occurrence counts incorrectly?

**Comment by mmcclenn** [comment]
Fixed. Rewrote interval filter logic in generateMainFilters().
